### ISSUE TITLE
License for our specs

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-charter#14]
All of our specifications at this time are under the (somewhat restrictive) [W3C Document license](https://www.w3.org/Consortium/Legal/copyright-documents).

Many W3C specs have switched to the more permissive [W3C Software and Document license](https://www.w3.org/Consortium/Legal/copyright-software) - this facilitates among other things exchanges with community groups.

Should we stick to our current license? Switch to the permissive one? Use a mix based on documents?

**Comment by aboba** [comment]
On Nov 22, 2017, at 7:31 AM, Dominique Hazael-Massieux <notifications@github.com> wrote:

> Many W3C specs have switched to the more permissive W3C Software and Document license - this facilitates among other things exchanges with community groups.

What does this additionally permit, specifically?

**Comment by dontcallmedom** [comment]
The Software & Document license is a usual open source license, which allows you to do pretty much whatever you want with the content of spec, including forking it, where the Document license does not allow modifications in general.

**Comment by alvestrand** [comment]
More permissive seems good (defuses arguments about reuse of IDL modules and so on).

**Comment by stefhak** [comment]
I agree to Harald's [comment](https://github.com/w3c/webrtc-charter/issues/14#issuecomment-349351412).
