### ISSUE TITLE
Adopt test as you commit policy in the charter

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-charter#15]
We've opted to [adopt a "test as you commit" policy for the main WebRTC spec](https://github.com/w3c/webrtc-pc/issues/1617). 

Should we commit to do so for all specs in our charter?

The current draft has possible text to that effect:
>  The Working Group will follow a [test as you commit approach](https://github.com/w3c/testing-how-to/#test-as-you-commit) to specification development, for specifications with one or more implementations.

**Comment by stefhak** [comment]
I think that what is in the current draft looks good.
