### ISSUE TITLE
Add language on "Using the Stream API to access data channels"

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-charter#19]
We should have as part of our plan that we'll use the Stream API (which solves things like writing exceedingly large chunks) to access DataChannel data transfer functionality.

(The details of how it's used don't belong in the charter)

**Comment by aboba** [comment]
@alvestrand The [charter](https://rawgit.com/w3c/webrtc-charter/gh-pages/webrtc-charter.html) does not include APIs for the transfer of data between peers in Sections 1 and 2, so perhaps we can start with that.
