### ISSUE TITLE
Update milestones table

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-charter#21]

**Comment by dontcallmedom** [comment]
I propose we only define milestones for the specs that need the most visible tracking (since that's what has been done in other charters) - to which I elect getUserMedia, WebRTC 1.0, and vNext (because it's new).

The dates are starting for discussions - please provide input where they seem too optimistic or pessimistic (ideally, with reasoning and alternate dates for the related milestones)

 Media Capture and Streams:
* updated CR in Q2 2018
* PR in Q4 2018
* Rec in Q1 2019

 WebRTC 1.0
* updated CR in Q2 2018
* PR in Q4 2018
* Rec in Q1 2019

 vNext specs:
* FPWD Q3 2018
* CR Q2 2019

**Comment by aboba** [comment]
I don't think it is realistic for WebRTC 1.0 to reach updated CR in Q2 2018 given that the bug count is stationary at best.  This probably won't happen until Q1 2019 at the earliest.  and that would put PR out until Q1 2020, with Recommendation unlikely to happen within the timeline of this charter.

**Comment by dontcallmedom** [comment]
done via #37
