### ISSUE TITLE
WebRTC 1.0 is already in CR, change text?

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-charter#26]
`In recognition of this interest, the Working Group will, once WebRTC 1.0: Real-time Communication Between Browsers reaches Candidate Recommendation, start work on a new set of object-oriented APIs for real-time communication.` -> `In recognition of this the Working Group will start work on a new set of object-oriented APIs for real-time communication.` ?

**Comment by aboba** [comment]
@stefhak I think it depends on the deliverables - the WebRTC-ICE specification is a "new object-oriented API", so if it remains in the charter, then your change would make sense.

**Comment by dontcallmedom** [comment]
depends on #27

**Comment by stefhak** [comment]
I'll do a PR.
