### ISSUE TITLE
Do we need words about access to raw data?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-charter#31]
Threads have discussed that it's hard with the current API to get access to "raw data" for audio / video (whatever that is).
Do we need text in the charter to explicitly say that this is within scope for the WG?

**Comment by maryroseMXXXVI** [comment]
By what

**Comment by maryroseMXXXVI** [comment]
I don't think you need access if I grant your request they do   will ask the  same

**Comment by gaperik** [comment]
Yes. How to best access the audio/video flows for training and actuation in WebRTC app's need of course to be looked info further and it may well be that most if the impact is outside the WebRTC API. It cannot however at this point be excluded that also WebRTC v2 API will be affected. Moreover, coordination by this WG with other API WG's can be expected. To avoid misunderstandings, I would suggest text opening up for this input would be appropriate, following the principle of "better safe than sorry", :-).

**Comment by stefhak** [comment]
@gaperik does #32 look good to you?
