### ISSUE TITLE
Add Data Transfer to Success Criteria

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-charter#39]
From Nils: https://lists.w3.org/Archives/Public/public-webrtc/2018Feb/0080.html

"One small improvement suggestion:

Since the data transfer got explicitly added to the scope of the working group I think it should get added to the success criteria as well. I would suggest to extend the success criteria to something like “… (that is, bidirectional audio and video communication and data transfer between the implementations)…"

Best
  Nils Ohlmeier"

**Comment by vivienlacourba** [comment]
@dontcallmedom @aboba can we close this issue as the relevant PR was merged ?
