### ISSUE TITLE
Collaboration with IETF

### ISSUE THREAD

**Issue by michaelchampion** [w3c/webrtc-charter#42]
The draft charter has several references to the IETF RTCWEB Working Group.   The RTCWEB WG was a focal point of prior collaboration with the IETF, but now that the WG is closing, substituting the entire Applications and Real-Time Area seems like too vague a substitute.
It would better to specify the particular ART WGs (e.g. ICE) that are relevant.

**Comment by alvestrand** [comment]
We do have the specific WGs listed, but the ART area can create WGs at any time, so not mentioning the ART area as a whole would be a mistake.

**Comment by aboba** [comment]
How is the protocol functionality to be supported in 2.0 to be determined?  To guide its work, WebRTC 1.0 used the "use cases" developed by the RTCWEB WG [RFC 7478. ](https://tools.ietf.org/html/rfc7478). For the 2.0 work, will the WEBRTC WG develop a new set of use cases, or will this be developed by a specific IETF WG?  Or will RFC 7478 continue to guide the new work?

**Comment by stefhak** [comment]
@michaelchampion the current draft already mentions the MMUSIC, AVTEXT, ICE and QUIC working groups under the ART heading. As ART can create and close WGs at any time we figured this would be the best way. Do you think those WGs should have their own headings?

**Comment by michaelchampion** [comment]
Thanks for the ping @stefhak . Yes, Microsoft is OK with the current draft charter language and you can close the issue.
