### ISSUE TITLE
Use case document for WebRTC 2.0

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-charter#48]
Will the WEBRTC WG be producing a use case document for WebRTC 2.0?  Or do the use cases in [RFC 7478](https://tools.ietf.org/html/rfc7478) still apply?

**Comment by lgrahl** [comment]
Mh, I've seen that RFC for the first time now and it's definitely lacking non A/V use cases. I'm certain we can provide a bunch of them. /cc @steely-glint

**Comment by aboba** [comment]
@lgrahl Thanks for your interest in helping out with the use cases. Was surprised that the original charter didn't even include data transfer in the success criteria.

**Comment by lgrahl** [comment]
I hope you don't mind if I drop a few notes here for use cases:

* Data Transfer
  - A large file sharing application (high throughput, flow control, reliable)
  - A web terminal (low throughput, reliable)
  - Controlling a drone or a robot (low throughput, low latency, partially reliable/unreliable)
  - P2P CDNs or traditional CDNs assisted by that (moderate throughput, scalability)
* Support for Web Workers
  - Background data processing without blocking the main loop
  - (Other use cases have been mentioned in https://github.com/w3c/webrtc-pc/issues/230)
