### ISSUE TITLE
Two browser or removal requirement

### ISSUE THREAD

**Issue by ekr** [w3c/webrtc-charter#51]
>  The highest priority of the group in this charter period will be to
> get the core recommendations progressed towards Recommendation
>   status. To that end, features that are not demonstrated to be> 
>  implemented by at least two browsers withih the timeframes indicated
>  will be removed from the specifications. Depending on their nature,
>  they may be republished as extension specification, or simply
>  dropped.

I have three concerns about this:

1. Procedurally, this doesn't actually have consensus in the WG. As far as I can tell, there was never any call for consensus on this point (or this proposed charter), If I'm wrong, please point me to it

2. It reflects a reversal of the basic understanding that we would make decisions on a consensus  basis. I don't have a problem with the WG deciding to remove features, but that should be a WG decision, with holding the spec until there is consensus on how to proceed as an option.

3. This is particularly problematic in WebRTC, which is explicitly a collaboration with IETF, and thus decisions need to be made jointly.

**Comment by dontcallmedom** [comment]
(clean-up, this was solved as part of the discussions of the now approved webrtc charter)
