### ISSUE TITLE
Update MEIG description

### ISSUE THREAD

**Issue by chrisn** [w3c/webrtc-charter#78]
The charter currently says that MEIG is working on Home Networking scenarios, but this is not a current active area of work in MEIG. I suggest updating the charter to say something like this:

> The Media and Entertainment Interest Group may uncover aspects that affect the design of real-time communications functions, e.g., on use of WebRTC for streaming of entertainment media content. The WebRTC Working Group will coordinate with the Interest Group on these use cases and requirements as appropriate.

**Comment by dontcallmedom** [comment]
my apologies, I completely missed this during the previous cycle of charter update; I've prepared #80 to make sure this gets fixed next time around.

**Comment by chrisn** [comment]
That's OK, and thank you!
